plugins {
    id 'java'
}

group = 'com.bellj'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation("com.amazonaws:aws-lambda-java-core:1.4.0")

    implementation "com.squareup.moshi:moshi:1.15.2"
    implementation "com.squareup.moshi:moshi-adapters:1.15.2"
    implementation("com.google.dagger:dagger:2.57.2")
    implementation 'jakarta.inject:jakarta.inject-api:2.0.1'

    annotationProcessor("com.google.dagger:dagger-compiler:2.57.2")


    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}